/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE IF NOT EXISTS `character` (
  `idChar` int(11) NOT NULL AUTO_INCREMENT,
  `short` varchar(50) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`idChar`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `move` (
  `idMove` int(11) NOT NULL AUTO_INCREMENT,
  `idChar_FK` int(11) DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `input` varchar(50) DEFAULT NULL,
  `damage` varchar(50) DEFAULT NULL,
  `guard` varchar(50) DEFAULT NULL,
  `startup` varchar(50) DEFAULT NULL,
  `active` varchar(50) DEFAULT NULL,
  `recovery` varchar(50) DEFAULT NULL,
  `onBlock` varchar(100) DEFAULT NULL,
  `onHit` varchar(50) DEFAULT NULL,
  `invuln` varchar(100) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`idMove`),
  KEY `FK_move_character` (`idChar_FK`),
  CONSTRAINT `FK_move_character` FOREIGN KEY (`idChar_FK`) REFERENCES `character` (`idChar`) ON DELETE SET NULL ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=842 DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
